### ISSUE TITLE
Support simple exponential fog

### ISSUE THREAD

**Issue by rdb** [Moguri/panda3d-simplepbr#10]
This is what the Shader Generator does for exponential fog:
```
result.rgb = lerp(attr_fogcolor.rgb, result.rgb, saturate(exp2(attr_fog.x * l_hpos.z * -1.442695f)))
```
I think this would be a useful addition, since fog is quite commonly used to hide draw distances.

In Panda3D, these attributes are provided through the p3d_Fog structure.

**Comment by Moguri** [comment]
I chose to use the exponential fog equation outlined in the OpenGL spec for [glFog](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glFog.xml), which has some differences to the Shader Generator code:
* It uses a natural exponent instead of a base-2 exponent
* It does not use this `-1.442695` value, I am not sure what that is for
* I chose (what I think is) the fog coordinate over using the fragment depth

Also, it appears that `p3d_Fog.density` does not default to 0, so by default there is a heavy fog unless the user sets up fog. For this reason, I have put the fog behind an explicit enable.

**Comment by rdb** [comment]
I think Cg had no natural exponent, and therefore needed the extra constant multiplication, but I could be wrong.

Come to think of it, given that this is PBR, we should probably investigate which fog method is the most physically accurate, and implement that here (and in Panda, if it isn't already).

`p3d_Fog.density` not defaulting to 0 is going on my post-PyWeek bug list, thanks for pointing that out.
