### ISSUE TITLE
Hardware skinning auto-detection fails

### ISSUE THREAD

**Issue by Epihaius** [Moguri/panda3d-simplepbr#34]
Hi,

In my case it seems that auto-detection of hardware skinning capabilities fails (both on a desktop PC with Nvidia card and on a laptop with integrated Intel chip -- both should have latest drivers installed).

Obviously, the real problem here is that my exact version of OpenGL is not correctly detected, as the `Pipeline._set_use_330` method (in `simplepbr/__init__.py`) wrongly sets the `self.use_330` variable to `False`, leading to the following errors:

```
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader created-shader:
created-shader(36) : error C7532: global type uvec4 requires "#version 130" or later
created-shader(36) : error C0000: ... or #extension GL_EXT_gpu_shader4 : enable
created-shader(36) : error C7507: OpenGL does not allow attributes of type uvec4
```

While explicitly passing `use_330=True` to `simplepbr.init` solves the problem, I was wondering if handling a request to enable hardware skinning couldn't simply set `self.use_330` to `True`?
After all, if the hardware really doesn't support OpenGL version 3.30, then errors would occur in *both* cases, wouldn't they?

So instead of this code in `Pipeline.__init__`:

```python
        self._set_use_330(use_330)
        self.enable_hardware_skinning = use_hardware_skinning if use_hardware_skinning is not None else self.use_330
```

the following might be preferred:

```python
        self._set_use_330(use_330)
        if use_hardware_skinning is None:
            self.enable_hardware_skinning = self.use_330
        elif use_hardware_skinning:
            self.enable_hardware_skinning = True
            self.use_330 = True
        else:
            self.enable_hardware_skinning = False
```

Of course, in this case a request like:

```python
simplepbr.init(use_hardware_skinning=True, use_330=False)
```

would make `use_hardware_skinning` take precedence over `use_330`, but I feel that to make sense (in an otherwise arguably nonsensical request).

What do you think?

---

On a side note, when enabling hardware skinning does succeed, there is still a (harmless) warning related to version 120:

```
created-shader(14) : warning C7533: global variable gl_FragColor is deprecated after version 120
:display:gsg:glgsg(warning): Shader created-shader produced the following warnings:
Fragment info
-------------
0(14) : warning C7533: global variable gl_FragColor is deprecated after version 120
```

Not exactly sure where that one is coming from, though. Could be either from `shadow.frag` or `tonemap.frag`, although both do use version 120.

**Comment by rdb** [comment]
Should hardware skinning really require GLSL 3.30, though?  It just requires 1.30.

**Comment by Epihaius** [comment]
> It just requires 1.30.

In that case:

1. Do you feel that it is acceptable to raise the minimum supported shader version from 1.20 to 1.30?
This would certainly obviate the need to modify the shader strings by replacing `attribute`/`varying` with `in`/`out`.

2. If dropping support for 1.20 is out of the question, can the maximum supported version be lowered from 3.30 to 1.30?
To be honest, I'm not sure which features of simplepbr *do* require 3.30, but since support for it was explicitly added, there must be a good reason, I assume.

3. If neither of the above is acceptable, is it worth further complicating the modification of the shader strings to convert them to one of not two but three different shader versions? Seems to me that it might become a bit messy.

**Comment by rdb** [comment]
Of course I can't answer for what @Moguri finds acceptable, but I think I can answer this:

> To be honest, I'm not sure which features of simplepbr _do_ require 3.30, but since support for it was explicitly added, there must be a good reason, I assume.

There are two good reasons:
* When using a core-only OpenGL profile, such as enabled with `gl-version 3 2`, GLSL versions older than 1.50 are not supported. This is in fact the only way to use modern OpenGL features on some systems, notably macOS.
* The new shader pipeline in Panda3D 1.11 will only support GLSL 3.30 and higher (with the trade-off that it can automatically transpile shaders back to 1.20 if needed). Having this feature in simplepbr today makes it possible to test the shader pipeline with games that use it and makes it ready for when it is merged.

Until the new shader pipeline is released, I think that support for 1.20 should be maintained, because we have users that are still limited to OpenGL 2.1.  Requiring GLSL 1.30 would shift the minimum requirement forward by a whole generation of graphics APIs.

**Comment by Moguri** [comment]
I'm in agreement with @rdb. I was planning to keep explicit GLSL 1.20 support until at least Panda 1.11 releases with the new shader pipeline.

I think we can fix this in the shader by trying to enable the GL_EXT_gpu_shader4 extension when we hit this corner. If this also fails, then the hardware truly doesn't support hardware skinning (well, not without charging vertex data to avoid uvec4).

**Comment by Epihaius** [comment]
> There are two good reasons:

Thanks for the explanation; that does make sense.

> I'm in agreement with @rdb. I was planning to keep explicit GLSL 1.20 support until at least Panda 1.11 releases with the new shader pipeline.

Fair enough.

> I think we can fix this in the shader by trying to enable the GL_EXT_gpu_shader4 extension when we hit this corner. If this also fails, then the hardware truly doesn't support hardware skinning (well, not without charging vertex data to avoid uvec4).

Sounds like a good solution.
Thanks in advance!

**Comment by Moguri** [comment]
Well, it looks like Mesa (tried Intel and AMD) does not like enabling `GL_EXT_gpu_shader4` with `#version 120`. I don't see another way to get `uvec` support for `#version 120`. I can at least add some better error handling. Probably something like if `use_hardware_skinning` is set but `use_330` is not (either automatically or explicitly), then disable hardware skinning and display a warning.

**Comment by rdb** [comment]
Is it possible to index into an array using a dynamic value at all in GLSL 1.20, perhaps using a float cast to int?  Trying to figure out if there is a way to support some kind of hardware instancing in GLSL 1.20 is one of the pending items to figure out for the shader pipeline.

**Comment by Moguri** [comment]
Yeah, we might be able to get away with a vec4 and some casting. We'll need to get the vertex data into the right format (can we use mungers for this)?

Although, we just need GLSL 130 for skinning. If the hardware really can only do 120, it probably doesn't have much overhead for hardware skinning *and* PBR. In other words, for the shader pipeline I'd consider:

* If GLSL 130+, then inject hardware skinning instructions
* Otherwise, fallback to software skinning (with a log message)

**Comment by rdb** [comment]
I don't think we need to munge the data, since OpenGL will be able to handle the cast internally (as long as we pass `false` for `normalized` to `glVertexAttribPointer`, but I think we are).  The question in my mind was whether GLSL 1.20 allows indexing into an array using a non-constant or non-dynamically-uniform expression.  But I just scanned the spec and it doesn't appear to be prohibited, and glslangValidator is OK with it too, so I think there's nothing in the way of supporting skinning in GLSL 1.20.

For the shader pipeline I think we still want to support skinning in GLSL 1.20, because macOS (and perhaps some other drivers) will only advertise GLSL 1.20 support in non-core-profile mode, even if they are capable of OpenGL 4.  It might be best to consider automatically translating an int attribute to float-and-cast so that users don't have to worry about this.  Probably easiest to handle this in SPIRV-Cross, actually, I'll have to consider filing a PR.

**Comment by Moguri** [comment]
Hardware skinning now works when using 120 shaders, but it may still issue warnings (or possibly fail) on some drivers, so I am still defaulting hardware skinning to off when 330 shaders are not being used.
